spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/peter
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: ERROR
    com:
      peter:
        hello: DEBUG

app:
  root-directory: /Users/augustine/Documents/
  security:
#    cors:
#      origin: http://localhost:8080
    jwt:
      keystore-location: keys/keystore.jks
      keystore-password: 232323
      key-alias: petersigning
      private-key-passphrase: 232323